# Generated by Django 4.2.21 on 2025-06-02 23:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default='Nível', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='Status',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(default='Tarefa', max_length=200),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='nivel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.nivel'),
        ),
    ]
