# Generated by Django 4.2.22 on 2025-06-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_nivel_delete_status_remove_tarefa_status_tarefa_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='indice',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='descricao',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
