# Generated by Django 4.2.22 on 2025-06-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_nivel_indice_alter_nivel_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nivel',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
