# Generated by Django 4.2.23 on 2025-06-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_alter_tarefa_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nivel',
            name='indice',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
