# Generated by Django 5.2.1 on 2025-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_alter_nivel_indice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='data',
            field=models.DateField(blank=True),
        ),
    ]
